### ISSUE TITLE
Deprecate this project

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-reporter-1.0-json#3]
I think we should deprecate/shut down this repo. The 1.0 JSON format is really old, the 2.0 format has been consistent through the last 3 major versions and maintaining this repo is a bit of an annoying overhead – it's fallen behind all the others.

We'd need to do the following:

- [x] Add a deprecation notice to this repo
- [x] Deprecate the [npm package](https://www.npmjs.com/package/pa11y-reporter-1.0-json)
- [x] Remove references to this repo from the [Pa11y README](https://github.com/pa11y/pa11y#reporters)

**Comment by andrewmee** [comment]
All complete.  Good night, sweet prince 😢
